SELECT DISTINCT v.name,
	v.flooring, CASE WHEN f.buy<>-1 THEN f.buy ELSE 0 END AS f_buy, f.diy,
	v.wallpaper, CASE WHEN w.buy<>-1 THEN w.buy ELSE 0 END AS w_buy, w.diy,
	CASE WHEN f.buy<>-1 AND w.buy<>-1 THEN f.buy+w.buy WHEN f.buy<>-1 THEN f.buy WHEN w.buy<>-1 THEN w.buy ELSE 0 END AS total
FROM villagers AS v, floors AS f, wallpaper AS w
WHERE v.flooring=f.name AND v.wallpaper=w.name
--FROM (villagers v JOIN floors f ON v.flooring=f.name) JOIN wallpaper w ON v.wallpaper=w.name
ORDER BY f.diy, w.diy;
